### PR TITLE
Improvements/1

### PR DESCRIPTION
**Pull request by sagzy**
This PR adapts the landing page for mobile.

I went ahead and also updated our footer, so that it's uses the crazy violet (looks cooler in my opinion and we can have our logo again in the footer) & so that it can be helpful for responsiveness. On mobile screen, I get rid of the header menu together and bring the pricing / about links to the footer. What do you think?

Screenshot 2021-11-25 at 19 23 02

Screenshot 2021-11-25 at 19 13 46

Screenshot 2021-11-25 at 19 21 40

The rest is pretty standard.

One thing that still needs to be fixed on embedded map is the search field - it's too big for mobile (see below).
Screenshot 2021-11-25 at 19 17 56

### CODE REVIEW

**Comment by shafy** [comment]
Looks good. Can you make the map a bit wider on mobile? I guess we should leave some space until we get the issue with the double touch sorted out.

**Comment by shafy** [comment]
Also, the subtitle on the main page should be "No code required" (not capitalized). Maybe you fixed this already :D

**Comment by sagzy** [comment]
Fixed the title, thanks! What do you mean wider? You mean have more space on the sides (less wide) so that the user can scroll more easily?

**Comment by shafy** [comment]
I mean less white space on the sides. Isn't that a good idea?

**Comment by sagzy** [comment]
Ah yes, I see what you mean now. It was not intentional. Fixed

**Review by shafy — APPROVED** [review]

**Pull request merged**
